name: "snyk-api-import"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'snyk-api-import'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_LOG_PATH: "."
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install snyk-api-import
    - name: Install snyk-api-import
      run: |
         sudo npm install snyk-api-import@latest -g
    # Run snyk-api-import
    - name: Run snyk-api-import
      run: |
         snyk-api-import --file=import-projects.json SNYK_LOG_PATH='~/my/path'
      continue-on-error: true
