name: Snyk SCA Scan

on:
  push:
    branches:
    - master

jobs:
  snyk_monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          # args: --all-projects --remote-repo-url=goof-github-actions
          args: --project-name=goof-github-actions --remote-repo-url=goof-github-actions
